// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: internal/code/code.proto

package code

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 公共Code错误码
type Error int32

const (
	Error_Unknown        Error = 0   // 未知错误
	Error_Success        Error = 200 // 操作成功
	Error_Internal       Error = 500 // 服务器内部错误
	Error_RecordNotFount Error = 600 // 服务器内部错误
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0:   "Unknown",
		200: "Success",
		500: "Internal",
		600: "RecordNotFount",
	}
	Error_value = map[string]int32{
		"Unknown":        0,
		"Success":        200,
		"Internal":       500,
		"RecordNotFount": 600,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_code_code_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_internal_code_code_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_internal_code_code_proto_rawDescGZIP(), []int{0}
}

var File_internal_code_code_proto protoreflect.FileDescriptor

var file_internal_code_code_proto_rawDesc = []byte{
	0x0a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x2f,
	0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2a, 0x46, 0x0a, 0x05, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00,
	0x12, 0x0c, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0xc8, 0x01, 0x12, 0x0d,
	0x0a, 0x08, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x10, 0xf4, 0x03, 0x12, 0x13, 0x0a,
	0x0e, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x74, 0x10,
	0xd8, 0x04, 0x42, 0x14, 0x5a, 0x12, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x63,
	0x6f, 0x64, 0x65, 0x3b, 0x63, 0x6f, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_code_code_proto_rawDescOnce sync.Once
	file_internal_code_code_proto_rawDescData = file_internal_code_code_proto_rawDesc
)

func file_internal_code_code_proto_rawDescGZIP() []byte {
	file_internal_code_code_proto_rawDescOnce.Do(func() {
		file_internal_code_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_code_code_proto_rawDescData)
	})
	return file_internal_code_code_proto_rawDescData
}

var file_internal_code_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_code_code_proto_goTypes = []interface{}{
	(Error)(0), // 0: Error
}
var file_internal_code_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_code_code_proto_init() }
func file_internal_code_code_proto_init() {
	if File_internal_code_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_code_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_code_code_proto_goTypes,
		DependencyIndexes: file_internal_code_code_proto_depIdxs,
		EnumInfos:         file_internal_code_code_proto_enumTypes,
	}.Build()
	File_internal_code_code_proto = out.File
	file_internal_code_code_proto_rawDesc = nil
	file_internal_code_code_proto_goTypes = nil
	file_internal_code_code_proto_depIdxs = nil
}
// Code impl
func (e Error) Code() int {
	return int(e) 
}
