# HTTP Server
[server]
	Address     = ":80"
	ServerAgent = "bazinga"
	LogPath     = "/tmp/log/bazinga/server"

# Logger.
[logger]
    Path        = "/tmp/log/bazinga"
    Level       = "PROD"
    Stdout      = false

# Database.
[database]
    link  = "mysql:root:root@tcp(127.0.0.1:3306)/test"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "/tmp/log/bazinga/sql"
        Level  = "all"
        Stdout = true