# HTTP Server
[server]
	Address         = ":80"
	ServerAgent     = "bazinga"
	LogPath         = "log/bazinga/server"
	DumpRouterMap   = true
	PProfEnabled    = true


[grpc]
    host = "127.0.0.1"
    port = 9000

[trace]
    enable = true
    addr = "127.0.0.1:6831"
    filter = ["ico", "jpg"]

# Logger.
[logger]
    Path        = "log/bazinga"
    Level       = "DEV"
    Stdout      = true

# Database.
[database]
    link  = "mysql:root:123456@tcp(127.0.0.1:3306)/bazinga"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "log/bazinga/sql"
        Level  = "all"
        Stdout = true

# Redis
[redis]
    default = "127.0.0.1:6379,0"